config/routes.rb
Rails.application.routes.draw do
  

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_for :admins
  root 'pages#home'
  
  get 'pages/webdesign'
  get 'pages/webdevelopment'
  get 'pages/mobileappdevelopment'
  get 'pages/seo'
  get 'pages/socialmediamanagement'
  get 'pages/googleanalytics'
  
  
  resources :potentialclients
  resources :posts
  
  get 'pages/work' => 'pages#work'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :storage => :s3,
                     :url => ':s3_alias_url',
                    :path => "/:class/:id/:style/:clean_filename",
                    :s3_host_alias => 'happyfellasblog.s3-us-west-2.amazonaws.com',
                    :s3_credentials => {
                      :bucket => ENV['S3_BUCKET_NAME'],
                      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
                    },
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
    friendly_id :title, use: :slugged
    
  belongs_to :user
end

app/models/potentialclient.rb
class Potentialclient < ActiveRecord::Base
  
  
  validates :email, :presence => {:message => 'Email cannot be blank, Mail not sent'}
   validates :fullname, :presence => {:message => 'Full Name cannot be blank, Mail not sent'}
   validates :fullname, :length => {:in => 6..60}
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title ="Web design Gujarat India. Happyfellas, the best website designers in Gujarat India."
    @metadesc= "Best web designers in Gujarat India. Affordable web design for e-commerce stores, Blog shops, comapny websites. Responisve web design at it's best."
    @metakeywords = "Web design Gujarat India, web designers Gujarat India, web designers, web design, wordpress web design, wordpress template, magento design customisation Gujarat India"
    @potentialclient = Potentialclient.new
  end
  
  def work
    @title ="Web design and web development portfolio Gujarat India - Happyfellas web studio"
    @metadesc= "Work samples of web designers from happyfellas.com. We have worked on various technologies like Magento, Wordpress, Joomla, Ruby on Rails etc."
    @metakeywords = "Web design portfolio Gujarat India, web designers portofolio Gujarat India, web designers portfolio, web design portfolio, wordpress web design work, wordpress template, magento design customisation case-study Gujarat India"
  end
  
  def webdesign
  end
  
  def webdevelopment
  end
  
  def mobileappdevelopment
  end
  
  def seo
  end
  
  def socialmediamanagement
  end
  
  def googleanalytics
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :authenticate_user! ,except: [:index, :show]
  layout "blog"
  
  
  def index
    @posts = Post.friendly.all.paginate :page => params[:page],:per_page=>30
  end

  def new
    @post = current_user.posts.new
  end

  def create
     @post = current_user.posts.build(post_params())
     if @post.save
       flash[:success] = "post created!"
       redirect_to root_url
     else
       render :new
     end
   end
   
   def show
     @post = Post.friendly.find(params[:id])
   end 
   
   def edit
      @post = Post.friendly.find(params[:id])
    end
    
    def update
       @post = Post.friendly.find(params[:id])
        if @post.update(post_params())
          flash[:success] = "post created!"
          redirect_to root_url
        else
          render :edit
        end
     end

   def destroy
     @Post.friendly.destroy
     redirect_to root_url
   end

   private

     def post_params
       params.require(:post).permit(:title, :body)
     end
 
end

app/controllers/potentialclients_controller.rb
class PotentialclientsController < ApplicationController
  
  before_filter :authenticate_admin!, only: [:index,:edit, :edit, :update, :destroy]
  before_action :set_potentialclient, only: [:show, :edit, :update, :destroy]

  # GET /potentialclients
  # GET /potentialclients.json
  def index
    @potentialclients = Potentialclient.all
  end

  # GET /potentialclients/1
  # GET /potentialclients/1.json
  def show
  end

  # GET /potentialclients/new
  def new
    @potentialclient = Potentialclient.new
  end

  # GET /potentialclients/1/edit
  def edit
  end

  # POST /potentialclients
  # POST /potentialclients.json
  def create
    @potentialclient = Potentialclient.new(potentialclient_params)

    respond_to do |format|
      if @potentialclient.save
        format.html { redirect_to @potentialclient, notice: 'Potentialclient was successfully created.' }
        format.json { render :show, status: :created, location: @potentialclient }
      else
        format.html { render :new }
        format.json { render json: @potentialclient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /potentialclients/1
  # PATCH/PUT /potentialclients/1.json
  def update
    respond_to do |format|
      if @potentialclient.update(potentialclient_params)
        format.html { redirect_to @potentialclient, notice: 'Potentialclient was successfully updated.' }
        format.json { render :show, status: :ok, location: @potentialclient }
      else
        format.html { render :edit }
        format.json { render json: @potentialclient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /potentialclients/1
  # DELETE /potentialclients/1.json
  def destroy
    @potentialclient.destroy
    respond_to do |format|
      format.html { redirect_to potentialclients_url, notice: 'Potentialclient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_potentialclient
      @potentialclient = Potentialclient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def potentialclient_params
      params.require(:potentialclient).permit(:email, :fullname, :worktype, :budget)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/potentialclients_helper.rb
module PotentialclientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title><%= @title %></title>
	<meta name="viewport" content="initial-scale=1">
	<meta name="description" content="<%= @metadesc %>">
	<meta name="keywords" content="<%= @metakeywords %>">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Kameron:700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,900' rel='stylesheet' type='text/css'>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52593315-2', 'auto');
  ga('send', 'pageview');

</script>
</head>

<body>
	<header class="main-page">
			<nav class="navbar navbar-default offshadow" role="navigation">
			  <div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
				<h4>
					<a class="navbar-brand" href="/">
						<img src="/assets/smiley.png" height="28" width="28" />
					happyfellas.com</a>
				</h4>
			    </div>
				

			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			 
			 			<ul class="nav navbar-nav navbar-right">
							<li><a href="/">Home</a></li>
						    <li><a href="/pages/work">Work</a></li>
						    <li><a href="/posts">Blog</a></li>
						</ul>
			
		
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>
	</header>

<%= yield %>
<footer>
<span>made with smiles by</span>
<a href="http://happyfellas.com" class="brand">happyfellas.com</a> 
</footer>
</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= (yield(:title) + " - " unless yield(:title).blank?).to_s + "Happyfellas" %></title>
	<meta name="viewport" content="initial-scale=1">
	<meta name="description" content="<%= @metadesc %>">
	<meta name="keywords" content="<%= @metakeywords %>">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Kameron:700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,900' rel='stylesheet' type='text/css'>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52593315-2', 'auto');
  ga('send', 'pageview');

</script>
</head>

<body>
	<header>
			<nav class="navbar navbar-default offshadow" role="navigation">
			  <div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
				<h4>
					<a class="navbar-brand" href="/">
						<img src="/assets/smiley.png" height="28" width="28" />
					happyfellas.com</a>
				</h4>
			    </div>
				

			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			 
			 			<ul class="nav navbar-nav navbar-right">
							<li><a href="/">Home</a></li>
						    <li><a href="/pages/work">Work</a></li>
						    <li><a href="/posts">Blog</a></li>
						</ul>
			
		
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>
	</header>

<div class="container">
<%= yield %>
</div>
<footer>
<div class="container">
<span>made with smiles by</span>
<a href="http://happyfellas.com" class="brand">happyfellas.com</a> 
</div>
</footer>
</body>
</html>

app/views/pages/home.html.erb
<section class="hero">
<div class="container">
	<div class="row">
	<div class="col-md-6 col-sm-6 col-xs-12">
	
<h1>Web Design company in Gujarat India that helps you earn more money</h1>

<p class="main tagline">We are a professional digital marketing agency passionate about providing the market with all-in-one, innovative and result focused solutions for any thriving, ambitious businesses – from individual freelancing companies to established corporations. </p>
<a class="signup button" data-toggle="modal" data-target="#something" href="#">Contact us now!</a>
</div>
	<div class="col-md-6 col-sm-6 col-xs-12">
			<div class="video-container offshadow">
				
				<!--<iframe width="640" height="360" src="//www.youtube.com/embed/n3TIkzKs-k0?rel=0" frameborder="0" allowfullscreen></iframe>
				-->
				
				<iframe src="//player.vimeo.com/video/118091654" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> 
				
				</div>
			
			
</div>
<div class="modal fade" id="something" tabindex="-1" role="dialog" aria-labelledby="somethingLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1 class="modal-title hero" id="somethingLabel">Send us an email</h1>
      </div>
      <div class="modal-body">
		<%= form_for(@potentialclient,:html => {:class =>"popup"}, :url => '/potentialclients', :method => 'POST') do |f| %>
		 	<div class="form-group">
			<div class="input-group-lg">
		 <%= f.email_field :email, :class=> "form-control required", :placeholder=>"My Email address is", :required => true %>
		 <%= f.text_field :fullname, :class=> "form-control required", :placeholder=>"My Full Name is ", :required => true %><br/><br/>
		<%= f.label :worktype, "I want you to make " %>
			<%= f.select :worktype , [ ['Website','Website'], ['Software','Software'], ['Mobile App','Mobile App'], ['SEO campaign','SEO campaign'], ['Social Media Campaign','Social Media Campaign'], ['All of them','All of them']],  :autofocus => true, :class=> "form-control"%><br/><br/>
			<%= f.label :budget, "And my budget is" %>
			
			<%= f.select :budget , [['Under 1000', 'Under 1000'], ['1000-2500','1000-2500'], ['2500-5000','2500-5000'], ['5000-10000','5000-10000'], ['Above 10000','Above 10000']],  :autofocus => true, :class=> "form-control"%>
		
		</div>
		</div>
		
		</div>


      </div>
      <div class="modal-footer">
        	<div class="form-group"> <%= f.submit "Send", :disable_with => 'Sending...', :class =>"btn btn-primary btn-lg" %></div>
		<% end %>
      </div>
    </div>
  </div>
</div>
</div>

</div>
</section>
<section class="short-intro softshadow">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
		<h1>Hire a web design agency in Gujarat India<br/><span class="yellow"> that makes you money 24x7</span></h1>
		</div>
		
		<p class="pull pull-left col-md-6 col-sm-6 col-xs-12">
			Our website design, optimisation and conversion efforts are performed with a single purpose – engaging the visitors who land on your website and increasing the chances that they takes the action you want them to take, such as purchasing your products, signing up for newsletter, downloading documents, filling surveys and more. </p><p class="pull pull-left col-md-6 col-sm-6 col-xs-12">
			Our on – site web design, and development are complimented with a professional marketing service tailored to boost the number of quality, targeted visitors interested in your website. </p><p class="pull pull-right col-md-6 col-sm-6 col-xs-12">
			By generating high amounts of traffic coming from your targeted demographic and budgetary requirements you will be able to significantly improve your business conversions, sales and ultimately – profits. </p><p class="pull pull-right col-md-6 col-sm-6 col-xs-12">
			Since 2006 we have grown from a small local website design company to an international digital marketing agency serving companies and corporations worldwide. Our approach to web development and marketing is dedicated, passionate and innovative focus on your long term success and development. </p><p class="normal col-md-12 col-sm-12 col-xs-12">
			You can consider us as one of your long term online partners always working with you to your success.
			</p><div class="col-md-2 col-sm-3 col-xs-12"></div>
			<img src="assets/devices.png" alt="image of all devices we work on" class="photo popout col-md-8 col-sm-6 col-xs-12" />
			<div class="col-md-2 col-sm-3 col-xs-12"></div>
		</div>
		</div>
	</section>
<section class="features">
<div class="container">

<div class="simple feature row">
  <div class="graphic col-md-6 col-sm-6 col-xs-12">
    <h2>Web and mobile application development team</h2>
  </div>

  <div class="copy col-md-6 col-sm-6 col-xs-12">
    <p>Our experienced web development professionals are fully aware of the value that highly innovative, well structured, functional and visually pleasing design provides to your business and impression it makes on the most important persons related to it – your clients. 
	We use sophisticated integration and branding techniques which ensure your potential customer is engaged from the moment he first visits your website – an impression that is crucial when building the necessary emotional relevance and connection with your viewer and building a relation between your company and client that results in trust and loyalty.</p>

  </div>
</div>

<div class="sources feature row">
	<div class="copy col-md-6 col-sm-6 col-xs-12">
	    <h2>We are Responsive web design experts</h2>

	    <p>We are a one stop service for everything you could possibly need to develop and make your online business project successful. Apart from web development, we pride ourselves in offering world class graphic design, social media marketing and SEO campaigns as well as top notch Mobile App Development.</p>
	  </div>
    <img alt="We do web responsive web design" src="assets/webdesign.png" class="col-md-6 col-sm-6 col-xs-12"/>

  	</div>


<div class="pricing feature row">

  <div class="graphic col-md-6 col-sm-6 col-xs-12">
	<small>Plans starting from as low as</small>
    <sup><em>$</em></sup> 99<sub>/mo</sub>
  </div>

  <div class="copy feature col-md-6 col-sm-6 col-xs-12">
    <h2>The SEO/SEM experts Gujarat India</h2>
    <p>Simply having an amazing website will do you no good if there are no visitors to see it. Our experts are here to make sure that never happens to you. Our Social Media and SEO experts will make sure that your media feeds are buzzing with activity that will produce a positive response and engage your followers and potential clients while keeping the whole process fun, informative and useful for everyone involved.</p>
  </div>

</div>

</div>

<a class="signup button" data-toggle="modal" data-target="#something2" href="#">Send us email!</a>

<div class="modal fade" id="something2" tabindex="-1" role="dialog" aria-labelledby="something2Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1 class="modal-title hero" id="somethingLabel">Send us an email</h1>
      </div>
      <div class="modal-body">
		<%= form_for(@potentialclient,:html => {:class =>"popup"}, :url => '/potentialclients', :method => 'POST') do |f| %>
		 	<div class="form-group">
			<div class="input-group-lg">
				 <%= f.email_field :email, :class=> "form-control required", :placeholder=>"My Email address is", :required => true %>
				 <%= f.text_field :fullname, :class=> "form-control required", :placeholder=>"My Full Name is ", :required => true %><br/><br/>
				<%= f.label :worktype, "I want you to make " %>
					<%= f.select :worktype , [ ['Website','Website'], ['Software','Software'], ['Mobile App','Mobile App'], ['SEO campaign','SEO campaign'], ['Social Media Campaign','Social Media Campaign'], ['All of them','All of them']],  :autofocus => true, :class=> "form-control"%><br/><br/>
					<%= f.label :budget, "And my budget is" %>

					<%= f.select :budget , [['Under 1000', 'Under 1000'], ['1000-2500','1000-2500'], ['2500-5000','2500-5000'], ['5000-10000','5000-10000'], ['Above 10000','Above 10000']],  :autofocus => true, :class=> "form-control"%>
		
		</div>
		</div>


      </div>
      <div class="modal-footer">
        	<div class="form-group"> <%= f.submit "Send", :disable_with => 'Sending...', :class =>"btn btn-primary btn-lg" %></div>
		<% end %>
      </div>
    </div>
  </div>
</div>



</section>
<!---
<section id="work" class="portfolio-content">
	<div class="container">
	 			<div class="port-head">
	 				<h1>Portfolio</h1>
	 				<p>Our work </p>
	 			</div>
				<div class="row">
				<div class="col-md-4 grid">
					<img src="/pflogo1.png" alt="portfolio of a web designer - happfellas" class="offshadow"/>
					<h4 class="centered-text">Design + Development</h4>
				</div>
				<div class="col-md-4 grid">
					<img src="/pflogo2.png" alt="portfolio of a web designer - happfellas" class="offshadow light"/>
					<h4 class="centered-text">Development + SEO</h4>
				</div>
				<div class="col-md-4 grid">
					<img src="/pflogo3.png" alt="portfolio of a web designer - happfellas" class="offshadow"/>
					<h4 class="centered-text">SEO + Social media integration</h4>
				</div>
				
		</div>				
</div>
</section>
-->
<section class="testimonial-text">

	<h1>What our clients say</h1>
	<div class="wrapper">
	    <div id="slider">
	        <span class="text-1"><p>You guys are awesome! Thank you so much, I'm impressed! Super fast, and thanks for the free tips and advice! I will be working with you agian soon<br/>
			<strong>Jilla Assaad</strong></p></span>
	        <span class="text-2"><p>Excellent job! We appreciate the professionalism and followup. Thank you!<br/>
			<strong>Dr. Janet Crain </strong></p></span>
	        <span class="text-3"><p>
				Great guys. Delivered work fast and had great communication. Highly recommend! <br/>
				<strong>Christina Graham</strong>
			</p></span>
	        <span class="text-4"><p>
				Great work! Quick, effective, and a great problem solvers. Looking forward to working with you again!<br/>
			<strong>Cassandra Freeman</strong>
			</p></span>
	    </div>
	</div>

</section>
<div id="more-footer" class="softshadow">
	<a href="#"><img src="/icons/Facebook.png" alt="facebook icon" /></a>
	<a href="#"><img src="/icons/Twitter.png" alt="facebook icon" /></a>
	<a href="#"><img src="/icons/Linkedin.png" alt="facebook icon" /></a>
	<a href="#"><img src="/icons/Youtube.png" alt="facebook icon" /></a>
</div>

<script type= "text/javscript">

</script>

app/views/pages/seo.html.erb
<div>
	<p>
	Our website design, optimisation and conversion efforts are performed with a single purpose – engaging the visitors who land on your website and increasing the chances that they takes the action you want them to take, such as purchasing your products, signing up for newsletter, downloading documents, filling surveys and more.</p><p>
	Our on – site web design, and development are complimented with a professional marketing service tailored to boost the number of quality, targeted visitors interested in your website. </p><p>
	By generating high amounts of traffic coming from your targeted demographic and budgetary requirements you will be able to significantly improve your business conversions, sales and ultimately – profits.</p><p>
	Since 2006 we have grown from a small local website design company to an international digital marketing agency serving companies and corporations worldwide. Our approach to web development and marketing is dedicated, passionate and innovative focus on your long term success and development.</p><p>
	You can consider us as one of your long term online partners always working with you to your success.</p>
</div>

app/views/posts/edit.html.erb
<section class="blog-content">
	<%= form_for @post, :class=>"form-horizontal",  :role => "form" do |f| %>
		<h3>Add a new post</h3>

	<div class="input-group-lg">
	<%= f.text_field :title, :class=> "form-control", :placeholder=>"Post title" %>
	</div>  



	<div class=" input-group-lg">
		<%= f.cktext_area :body,:class=> "form-control", :placeholder => "Write your post content here", :ckeditor => {:language => 'en'} %>
	</div> 

	<%= f.hidden_field :user_id, :value => current_user.id %>
	<div class="form-group form-submit col-md-12">
	<%= f.submit "Add New post", :disable_with => 'Adding...', :class =>"btn btn-black" %>
	<% end %>
</section>

app/views/potentialclients/edit.html.erb
<section class="hero">
<div class="container">
	<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
<%= render 'form' %>

<%= link_to 'Show', @potentialclient %> |
<%= link_to 'Back', potentialclients_path %>
</div>
</div>
</div>
</section>

app/views/potentialclients/index.html.erb
<section class="hero">
<div class="container">
	<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Fullname</th>
      <th>Worktype</th>
      <th>Budget</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @potentialclients.each do |potentialclient| %>
      <tr>
        <td><%= potentialclient.email %></td>
        <td><%= potentialclient.fullname %></td>
        <td><%= potentialclient.worktype %></td>
        <td><%= potentialclient.budget %></td>
        <td><%= link_to 'Show', potentialclient %></td>
        <td><%= link_to 'Edit', edit_potentialclient_path(potentialclient) %></td>
        <td><%= link_to 'Destroy', potentialclient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Potentialclient', new_potentialclient_path %>
</div>
</div>
</div>
</section>

app/views/potentialclients/new.html.erb
<section class="hero thankyoupage">
<div class="container">
<%= render 'form' %>
<div class="form-links">
<%= link_to 'Back', potentialclients_path %>
</div>
</div>
</section>

app/views/potentialclients/show.html.erb
<section class="hero thankyoupage">
<div class="container">
<h1>Thank you, your mail was sent</h1>	
<p class="main tagline">Someone from us will soon get in touch with you.Please feel free to browse till then, Go <%= link_to 'Back', root_url %> to the main page if you want to.</p>
</div>
</section>

app/views/potentialclients/thankyou.html.erb
<section class="hero thankyoupage">
<div class="container">
<h1>Thank you, your mail was sent</h1>	
<p class="main tagline">Someone from us will soon get in touch with you.Please feel free to browse till then, Go <%= link_to 'Back', potentialclients_path %> to the main page if you want to.</p>
</div>
</section>